### ISSUE TITLE
unocss v0.51.8 Integrate the perset and report an error

### ISSUE THREAD

**Issue by bytegolang** [zirbest/unocss-preset-primitives#5]
```js
// uno.config.ts
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetUno,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

import { presetKobalte } from 'unocss-preset-primitives'

export default defineConfig({
  shortcuts: [{
    sideSel: 'before:absolute before:content-none before:top-0 before:bottom-0 before:border-l-amber before:border-l-3 before:border-l-solid relative bg-amber bg-op5 bg- text-amber',
  }],
  theme: {
    colors: {
      // ...
    },
  },
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      extraProperties: {
        'display': 'inline-block',
        'height': '1.2em',
        'width': '1.2em',
        'vertical-align': 'text-bottom',
      },
    }),
    presetTypography(),
    presetWebFonts({
      fonts: {
        sans: 'Inter:400,600,800',
        mono: 'DM Mono',
      },
    }),
    presetKobalte(),
  ],
  transformers: [transformerDirectives(), transformerVariantGroup()],
})
```

error message
```js
Type 'Preset<{}>' is not assignable to type 'Preset<any> | Preset<any>[]'.
  Type 'Preset<{}>' is not assignable to type 'Preset<any>'.
    Types of property 'rules' are incompatible.
      Type 'Rule<{}>[] | undefined' is not assignable to type 'Rule<any>[] | undefined'.
        Type 'Rule<{}>[]' is not assignable to type 'Rule<any>[]'.
          Type 'Rule<{}>' is not assignable to type 'Rule<any>'.
            Type '[RegExp, DynamicMatcher<{}>]' is not assignable to type 'Rule<any>'.
              Type '[RegExp, DynamicMatcher<{}>]' is not assignable to type '[string, CSSObject | CSSEntries]'.
                Type at position 0 in source is not compatible with type at position 0 in target.
                  Type 'RegExp' is not assignable to type 'string'.
```

**Comment by zirbest** [comment]
fixed [v0.0.1-beta.6](https://github.com/zirbest/unocss-preset-primitives/releases/tag/v0.0.1-beta.6)

**Comment by izcream** [comment]
still have this type error on unocss 0.52.0 and unocss-preset-primitives 0.0.1-beta.6

![image](https://github.com/zirbest/unocss-preset-primitives/assets/10282500/370c7df8-8e1c-4e9b-aa10-ba66e928fd4c)

**Comment by zirbest** [comment]
@izcream 
can you reproduce the error

**Comment by izcream** [comment]
@zirbest  sorry for late reply

i have create repo for reproduce the error
you can clone and install(my case use pnpm) dependencies

[remix-uno-issue5](https://github.com/izcream/remix-uno-issue5)

**Comment by zirbest** [comment]
@izcream
The plugin is now working properly after I updated its dependencies.
fixed [v0.0.1-beta.7](https://github.com/zirbest/unocss-preset-primitives/releases/tag/v0.0.1-beta.7)

**Comment by izcream** [comment]
confirm working on `v0.0.1-beta.7` thanks🤩
![image](https://github.com/zirbest/unocss-preset-primitives/assets/10282500/de64e40e-f1e8-40d9-a545-37fe3c813714)

**Comment by Razboy20** [comment]
Still encountering the issue with `0.0.1-beta.7` with unocss `v0.53.1`.

**Comment by zirbest** [comment]
@Razboy20 done [v0.0.1-beta.8](https://github.com/zirbest/unocss-preset-primitives/releases/tag/v0.0.1-beta.8)

**Comment by MrFoxPro** [comment]
@zirbest still an error on `0.0.1-beta.9` :D

**Comment by zirbest** [comment]
@MrFoxPro  done [v0.0.1-beta.10](https://github.com/zirbest/unocss-preset-primitives/releases/tag/v0.0.1-beta.10)

**Comment by xsjcTony** [comment]
@zirbest still an error on `0.0.1-beta.10` 🤣
![image](https://github.com/zirbest/unocss-preset-primitives/assets/45784210/31d1a2e5-0cc8-4788-82fc-dd770d4b2202)

**Comment by zirbest** [comment]
@xsjcTony  [v0.0.1-beta.11](https://github.com/zirbest/unocss-preset-primitives/releases/tag/v0.0.1-beta.11)

> Is there a permanent solution for this?

I think GitHub Actions could be a helpful tool for this?

**Comment by xsjcTony** [comment]
Again🤣 `v0.56.2`
![image](https://github.com/zirbest/unocss-preset-primitives/assets/45784210/c30e5c19-cdb5-49f5-9336-44f82c4063be)

**Comment by zirbest** [comment]
@xsjcTony :smile: 
I will explore the possibility of using a GitHub Action to resolve this.
